controller:
  nodeSelector:
    role: jenkins-controller
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1.5Gi"

agent:
  enabled: true
  nodeSelector:
    role: jenkins-agent
  tolerations:
    - key: "jenkins"
      value: "agent"
      effect: "NoSchedule"
      operator: "Equal"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

persistence:
  enabled: true
  size: "10Gi"
  storageClass: "gp2" 